/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Airbrakes */

#ifndef _Included_Airbrakes
#define _Included_Airbrakes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Airbrakes
 * Method:    DragForce
 * Signature: (FFF)F
 */
JNIEXPORT jfloat JNICALL Java_Airbrakes_DragForce
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     Airbrakes
 * Method:    InitController
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Airbrakes_InitController
  (JNIEnv *, jclass);

/*
 * Class:     Airbrakes
 * Method:    RunControllerAndGetDeploymentPct
 * Signature: (FFFFFFFFFFF)F
 */
JNIEXPORT jfloat JNICALL Java_Airbrakes_RunControllerAndGetDeploymentPct
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     Airbrakes
 * Method:    RunControllerRawAndGetDeploymentPct
 * Signature: (FFFF)F
 */
JNIEXPORT jfloat JNICALL Java_Airbrakes_RunControllerRawAndGetDeploymentPct
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
