/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class space_bsli_AirbrakesExtension */

#ifndef _Included_space_bsli_AirbrakesExtension
#define _Included_space_bsli_AirbrakesExtension
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     space_bsli_AirbrakesExtension
 * Method:    SetRocketMass
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_space_bsli_AirbrakesExtension_SetRocketMass
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     space_bsli_AirbrakesExtension
 * Method:    SetTargetApogee
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_space_bsli_AirbrakesExtension_SetTargetApogee
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     space_bsli_AirbrakesExtension
 * Method:    DragForce
 * Signature: (FFF)F
 */
JNIEXPORT jfloat JNICALL Java_space_bsli_AirbrakesExtension_DragForce
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     space_bsli_AirbrakesExtension
 * Method:    InitController
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_space_bsli_AirbrakesExtension_InitController
  (JNIEnv *, jclass);

/*
 * Class:     space_bsli_AirbrakesExtension
 * Method:    RunControllerAndGetDeploymentPct
 * Signature: (FFFFFFFFFFF)F
 */
JNIEXPORT jfloat JNICALL Java_space_bsli_AirbrakesExtension_RunControllerAndGetDeploymentPct
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     space_bsli_AirbrakesExtension
 * Method:    RunControllerRawAndGetDeploymentPct
 * Signature: (FFFF)F
 */
JNIEXPORT jfloat JNICALL Java_space_bsli_AirbrakesExtension_RunControllerRawAndGetDeploymentPct
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
