#!/bin/sh

echo Forcefully overwriting existing kernel...
cp -ra usr/share/raspberrypi-linux-bsli/boot/* /boot
cp -ra usr/share/raspberrypi-linux-bsli/lib/* /lib

echo Forcefully overwriting existing config.txt...
cp -ra usr/share/bsli/config.txt /boot/firmware/config.txt
