/**
 *  error.h
 *  
 *  Standardized errors for our firmware
 *
 * @authors
 * - Diego Noria
 *
 * reference for how the enum to string works
 * https://stackoverflow.com/a/37277144
 */

#pragma once

#include <stdint.h>
#include <stdio.h>

// TODO finish ms5607 errors
// TODO remove generic FAILURE
#define FS_ERROR_NAMES \
  Cn(SUCCESS, 0) \
  C(FAILURE) \
  C(INSUFFICIENT_MEMORY) \
  C(I2C_READ_FAILURE) \
  C(I2C_READ_TIMEOUT) \
  C(I2C_WRITE_FAILURE) \
  C(I2C_WRITE_TIMEOUT) \
  C(I2C_REGISTER_READ_FAILURE) \
  C(I2C_REGISTER_READ_TIMEOUT) \
  C(I2C_REGISTER_WRITE_FAILURE) \
  C(I2C_REGISTER_WRITE_TIMEOUT) \
  C(ADXL375_DATA_READY_READ_FAILURE) \
  C(ADXL375_DEVICE_ID_MISMATCH) \
  C(ADXL375_DEVICE_ID_READ_FAILURE) \
  C(ADXL375_POWER_CONTROL_WRITE_FAILURE) \
  C(ADXL375_REQUEST_DATA_FORMAT_FAILURE) \
  C(ADXL375_WRITE_BW_RATE_FAILURE) \
  C(ADXL375_READ_ACCELERATION_FAILURE) \
  C(BM1422_WHO_AM_I_READ_FAILURE) \
  C(BM1422_WHO_AM_I_MISMATCH) \
  C(BM1422_CNTL1_WRITE_FAILURE) \
  C(BM1422_CNTL3_WRITE_FAILURE) \
  C(BM1422_CNTL4_WRITE_FAILURE) \
  C(BM1422_DATAX_READ_FAILURE) \
  C(BMI323_CHIP_ID_READ_FAILURE) \
  C(BMI323_CHIP_ID_MISMATCH) \
  C(BMI323_ERROR_REGISTER_READ_FAILURE) \
  C(BMI323_ERROR_REGISTER_FAILURE) \
  C(BMI323_STATUS_FAILURE) \
  C(BMI323_CONFIGURATION_FAILURE) \
  C(BMI323_ACC_CONF_READ_FAILURE) \
  C(BMI323_ACC_CONF_WRITE_FAILURE) \
  C(BMI323_GYRO_CONF_READ_FAILURE) \
  C(BMI323_GYRO_CONF_WRITE_FAILURE) \
  C(BMI323_INT_MAP_WRITE_FAILURE) \
  C(BMI323_DATAX_READ_FAILURE) \
  C(MS5607_PROM_READ_COMMAND_FAILURE) \
  C(MS5607_PROM_READ_DATA_FAILURE) \
  C(START_TEMPERATURE_CONVERSION_FAILURE) \
  C(READ_TEMPERATURE_DATA_FAILURE) \
  C(START_PRESSURE_CONVERSION_FAILURE) \
  C(READ_PRESSURE_DATA_FAILURE) \
  C(SENSOR_INITIALIZATION_FAILURE) \
  C(SD_CARD_INIT_FAILURE) \
  C(SD_CARD_FILE_OPEN_FAILURE) \
  C(FS_NOT_FOUND) \
  C(SERVO_OVER_CURRENT)
// Regular error
#define C(x) x,
// Error with specific number code
#define Cn(x, y) x=y,
// TOP is the number of errors total
enum FSError: uint8_t { FS_ERROR_NAMES TOP };
#undef C
#undef Cn

#define C(x) #x,    
#define Cn(x,y) #x,
static const char * __FC_error__strings[] = { FS_ERROR_NAMES };
static const char ** FCError__strings = &__FC_error__strings[0];
